# Project information
site_name: Dorna
site_url: https://dorna.noxian.dev/
site_author: Vinicius Rodrigues
site_description: >-
  Agregado de informações em português sobre o jogo Orna!

extra:
  generator: false

extra_css:
  - theme/assets/extra-dracula.css

copyright: Copyright &copy; 2023 Orna Players

markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
theme:
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.suggest
    - navigation.tracking
    - navigation.prune

  name: material
  custom_dir: docs/theme
  palette:
    scheme: dracula
    primary: deep purple
    accent: deep purple
  font:
    text: Roboto
    code: Roboto Mono
  
  logo: assets/logo.svg
  favicon: assets/logo.svg

  plugins:
  - social:
      enabled: true
      cards: true
      cards_layout: default
  - search:
      lang: pt
  language: pt-BR
