site_name: Dorna
site_url: https://dorna.noxian.dev/
extra:
  generator: false
copyright: Copyright &copy; 2023 Orna Players
markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
theme:
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.suggest
    - navigation.sections
  plugins:
  - social:
      enabled: true
      cards: true
      cards_layout: default
  - search:
      lang: pt
  language: pt-BR
  logo: assets/logo.svg
  favicon: assets/logo.svg
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: brown
      toggle:
        icon: material/weather-night
        name: Modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: brown
      toggle:
        icon: material/weather-sunny
        name: Modo claro
